# Generated by Django 3.2.3 on 2021-07-12 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210712_0100'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DetalleVenta',
        ),
    ]
